controller_manager:
  ros__parameters:
    update_rate: 1000
    use_sim_time: true

    position_cont:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

position_cont:
  ros__parameters:
    joints:
      - fixture_to_hip
      - hip_to_upper_leg
      - upper_leg_to_lower_leg

    command_interfaces:
    - position

    state_interfaces:
    - position
    - velocity

    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    open_loop_control: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      joint1:
        trajectory: 0.05
        goal: 0.03
